### ISSUE TITLE
.env configuration not working properly

### ISSUE THREAD

**Issue by felipeneuhauss** [MobieTrain/tech-challenge-backend#2]
Hi!

I've just tried to run the project following the instructions. But the env variables are not being properly loaded specifically speaking .env.dev. So in this case, should I solve the problem, like working some env package in order to handle it or could you give some clue?

After run `npm run local` I got:

```
ts-node-dev ver. 1.0.0-pre.62 (using ts-node ver. 8.10.2, typescript ver. 4.0.3)
Debugger listening on ws://127.0.0.1:7000/acd20989-c009-49bb-844e-404571696e3e
For help, see: https://nodejs.org/en/docs/inspector
Error: Missing ENV variable `API_SQL_HOST`.
    at Object.<anonymous> (/Users/felipeneuhauss/Workspace/challenge/tech-challenge-backend/src/knexfile.ts:5:41)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)

```

Thank you.

**Comment by gerardolima** [comment]
The project contains configuration for the recommended tool `direnv` (in [README](https://github.com/MobieTrain/tech-challenge-backend/blob/main/README.md)) to load the DEV environment variables from the file `.env.dev`. This is a recommended tool, though, so you can use an alternative way to load the environment variables, if you prefer.
